title: As Oy Hämeen Linnan Portti
theme: jekyll-theme-leap-day
url: https://valtterihalla.github.io/linnanportti/
repo: https://github.com/valtterihalla/linnanportti/
#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-Dinky
#theme: jekyll-theme-Hacker
#theme: jekyll-theme-Leap day
#theme: jekyll-theme-Merlot
#theme: jekyll-theme-Midnight
#theme: jekyll-theme-Minima
#theme: jekyll-theme-Minimal
#theme: jekyll-theme-Modernist
#theme: jekyll-theme-Slate
#theme: jekyll-theme-Tactile
#theme: jekyll-theme-Time machine
